Feature Engineering

In [76]:
import pandas as pd

In [85]:
clean_df = pd.read_csv('clean_data_after_eda.csv')
clean_df.head()

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,var_6m_price_off_peak_var,var_6m_price_peak_var,var_6m_price_mid_peak_var,var_6m_price_off_peak_fix,var_6m_price_peak_fix,var_6m_price_mid_peak_fix,var_6m_price_off_peak,var_6m_price_peak,var_6m_price_mid_peak,churn
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,6/15/13,6/15/16,11/1/15,6/23/15,0.00,...,0.000131,4.100000e-05,9.084740e-04,2.086294,99.530517,44.235794,2.086425,9.953056e+01,4.423670e+01,1
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,8/21/09,8/30/16,8/21/09,8/31/15,189.95,...,0.000003,1.217891e-03,0.000000e+00,0.009482,0.000000,0.000000,0.009485,1.217891e-03,0.000000e+00,0
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,4/16/10,4/16/16,4/16/10,4/17/15,47.96,...,0.000004,9.450000e-08,0.000000e+00,0.000000,0.000000,0.000000,0.000004,9.450000e-08,0.000000e+00,0
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,3/30/10,3/30/16,3/30/10,3/31/15,240.04,...,0.000003,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000003,0.000000e+00,0.000000e+00,0
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,1/13/10,3/7/16,1/13/10,3/9/15,445.75,...,0.000011,2.900000e-06,4.860000e-10,0.000000,0.000000,0.000000,0.000011,2.900000e-06,4.860000e-10,0

In [78]:
clean_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14606 entries, 0 to 14605
Data columns (total 44 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              14606 non-null  object
 1   channel_sales                   14606 non-null  object
 2   cons_12m                        14606 non-null  int64
 3   cons_gas_12m                    14606 non-null  int64
 4   cons_last_month                 14606 non-null  int64
 5   date_activ                      14606 non-null  object
 6   date_end                        14606 non-null  object
 7   date_modif_prod                 14606 non-null  object
 8   date_renewal                    14606 non-null  object
 9   forecast_cons_12m               14606 non-null  float64
 10  forecast_cons_year              14606 non-null  int64
 11  forecast_discount_energy        14606 non-null  int64
 12  forecast_meter_rent_12m         14606 non-null  float64
 13  forecast_price_energy_off_peak  14606 non-null  float64
 14  forecast_price_energy_peak      14606 non-null  float64
 15  forecast_price_pow_off_peak     14606 non-null  float64
 16  has_gas                         14606 non-null  object
 17  imp_cons                        14606 non-null  float64
 18  margin_gross_pow_ele            14606 non-null  float64
 19  margin_net_pow_ele              14606 non-null  float64
 20  nb_prod_act                     14606 non-null  int64
 21  net_margin                      14606 non-null  float64
 22  num_years_antig                 14606 non-null  int64
 23  origin_up                       14606 non-null  object
 24  pow_max                         14606 non-null  float64
 25  var_year_price_off_peak_var     14606 non-null  float64
 26  var_year_price_peak_var         14606 non-null  float64
 27  var_year_price_mid_peak_var     14606 non-null  float64
 28  var_year_price_off_peak_fix     14606 non-null  float64
 29  var_year_price_peak_fix         14606 non-null  float64
 30  var_year_price_mid_peak_fix     14606 non-null  float64
 31  var_year_price_off_peak         14606 non-null  float64
 32  var_year_price_peak             14606 non-null  float64
 33  var_year_price_mid_peak         14606 non-null  float64
 34  var_6m_price_off_peak_var       14606 non-null  float64
 35  var_6m_price_peak_var           14606 non-null  float64
 36  var_6m_price_mid_peak_var       14606 non-null  float64
 37  var_6m_price_off_peak_fix       14606 non-null  float64
 38  var_6m_price_peak_fix           14606 non-null  float64
 39  var_6m_price_mid_peak_fix       14606 non-null  float64
 40  var_6m_price_off_peak           14606 non-null  float64
 41  var_6m_price_peak               14606 non-null  float64
 42  var_6m_price_mid_peak           14606 non-null  float64
 43  churn                           14606 non-null  int64
dtypes: float64(28), int64(8), object(8)
memory usage: 4.9+ MB

In [79]:
#Changing date columns from object to date
date_columns_client = ['date_activ','date_end','date_modif_prod','date_renewal']

clean_df[date_columns_client] = clean_df[date_columns_client].apply(pd.to_datetime, format= '%m/%d/%y')

In [80]:
#CHecking for unique values
clean_df.nunique()

id                                14606
channel_sales                         8
cons_12m                          11065
cons_gas_12m                       2112
cons_last_month                    4751
date_activ                         1796
date_end                            368
date_modif_prod                    2129
date_renewal                        386
forecast_cons_12m                 13993
forecast_cons_year                 4218
forecast_discount_energy             12
forecast_meter_rent_12m            3528
forecast_price_energy_off_peak      516
forecast_price_energy_peak          329
forecast_price_pow_off_peak          41
has_gas                               2
imp_cons                           7752
margin_gross_pow_ele               2363
margin_net_pow_ele                 2363
nb_prod_act                          10
net_margin                        11965
num_years_antig                      13
origin_up                             6
pow_max                             698
var_year_price_off_peak_var        1712
var_year_price_peak_var            1426
var_year_price_mid_peak_var        1300
var_year_price_off_peak_fix         783
var_year_price_peak_fix             336
var_year_price_mid_peak_fix         337
var_year_price_off_peak            4634
var_year_price_peak                2318
var_year_price_mid_peak            1913
var_6m_price_off_peak_var          1016
var_6m_price_peak_var               783
var_6m_price_mid_peak_var           680
var_6m_price_off_peak_fix           206
var_6m_price_peak_fix                92
var_6m_price_mid_peak_fix            92
var_6m_price_off_peak              2064
var_6m_price_peak                  1163
var_6m_price_mid_peak               874
churn                                 2
dtype: int64

In [81]:
#Creating new month columns 
clean_df['date_activ_month'] = clean_df['date_activ'].dt.month

clean_df['date_end_month'] = clean_df['date_end'].dt.month

clean_df['date_modif_prod_month'] = clean_df['date_modif_prod'].dt.month

clean_df['date_renewal_month'] = clean_df['date_renewal'].dt.month

#Creating year columns

clean_df['date_activ_year'] = clean_df['date_activ'].dt.year

clean_df['date_end_year'] = clean_df['date_end'].dt.year

clean_df['date_modif_prod_year'] = clean_df['date_modif_prod'].dt.year

clean_df['date_renewal_year'] = clean_df['date_renewal'].dt.year

#Changing has_gas columns from object to int64
#lean_df['has_gas'] = clean_df['has_gas'].astype(int)

In [82]:
#Creating an extra for contraction duration
clean_df['contract_duration'] = (clean_df['date_end'] - clean_df['date_activ']).dt.days
clean_df.head(5)

,id,channel_sales,cons_12m,cons_gas_12m,cons_last_month,date_activ,date_end,date_modif_prod,date_renewal,forecast_cons_12m,...,churn,date_activ_month,date_end_month,date_modif_prod_month,date_renewal_month,date_activ_year,date_end_year,date_modif_prod_year,date_renewal_year,contract_duration
0,24011ae4ebbe3035111d65fa7c15bc57,foosdfpfkusacimwkcsosbicdxkicaua,0,54946,0,2013-06-15,2016-06-15,2015-11-01,2015-06-23,0.00,...,1,6,6,11,6,2013,2016,2015,2015,1096
1,d29c2c54acc38ff3c0614d0a653813dd,MISSING,4660,0,0,2009-08-21,2016-08-30,2009-08-21,2015-08-31,189.95,...,0,8,8,8,8,2009,2016,2009,2015,2566
2,764c75f661154dac3a6c254cd082ea7d,foosdfpfkusacimwkcsosbicdxkicaua,544,0,0,2010-04-16,2016-04-16,2010-04-16,2015-04-17,47.96,...,0,4,4,4,4,2010,2016,2010,2015,2192
3,bba03439a292a1e166f80264c16191cb,lmkebamcaaclubfxadlmueccxoimlema,1584,0,0,2010-03-30,2016-03-30,2010-03-30,2015-03-31,240.04,...,0,3,3,3,3,2010,2016,2010,2015,2192
4,149d57cf92fc41cf94415803a877cb4b,MISSING,4425,0,526,2010-01-13,2016-03-07,2010-01-13,2015-03-09,445.75,...,0,1,3,1,3,2010,2016,2010,2015,2245

In [87]:
#Column for difference between prices for off peak and peak (energy)
clean_df['var_year_price_op_difference_var'] = (clean_df['var_year_price_off_peak_var'] - clean_df['var_year_price_peak_var'])

#Column for difference between prices for off peak and mid - peak(enrgy)
clean_df['var_year_price_om_difference_var'] = (clean_df['var_year_price_off_peak_var'] - clean_df['var_year_price_mid_peak_var'])

#Column for difference between prices for  peak and mid peak(energy)

clean_df['var_year_price_pm_difference_var'] = (clean_df['var_year_price_peak_var'] - clean_df['var_year_price_mid_peak'])

#Column for difference between prices for off peak and peak(power)
clean_df['var_year_price_op_difference_var'] = (clean_df['var_year_price_off_peak_fix'] - clean_df['var_year_price_peak_fix'])

#Column for difference between prices for off peak and mid - peak(power)
clean_df['var_year_price_om_difference_var'] = (clean_df['var_year_price_off_peak_fix'] - clean_df['var_year_price_mid_peak_fix'])

#Column for difference between prices for  peak and mid peak(power)

clean_df['var_year_price_pm_difference_var'] = (clean_df['var_year_price_peak_fix'] - clean_df['var_year_price_mid_peak_fix'])

In [84]:
#Dropping the these columns since they do not seem to contribute to why customers could be churning


clean_df = clean_df.drop('margin_net_pow_ele', axis=1)


clean_df = clean_df.drop('margin_gross_pow_ele', axis=1)